import asyncio
import os
import pytest

from nillion_client import (
    Network,
    NilChainPayer,
    NilChainPrivateKey,
    VmClient,
    PrivateKey,
)
from dotenv import load_dotenv

from config import CONFIG_PROGRAM_NAME, CONFIG_PARTY_1

home = os.getenv("HOME")
load_dotenv(f"{home}/.config/nillion/nillion-devnet.env")


# The 1st Party stores a secret
async def main():
    # Use the devnet configuration generated by `nillion-devnet`
    network = Network.from_config("devnet")

    # Create payments config and set up Nillion wallet with a private key to pay for operations
    nilchain_key: str = os.getenv("NILLION_NILCHAIN_PRIVATE_KEY_0")  # type: ignore
    payer = NilChainPayer(
        network,
        wallet_private_key=NilChainPrivateKey(bytes.fromhex(nilchain_key)),
        gas_limit=10000000,
    )

    # We will identify ourselves with the pre-configured private key
    signing_key = PrivateKey(CONFIG_PARTY_1["private_key"])
    client = await VmClient.create(signing_key, network, payer)

    user_id = client.user_id
    program_mir_path = f"../nada_programs/target/{CONFIG_PROGRAM_NAME}.nada.bin"

    # Adding funds to the client balance so the upcoming operations can be paid for
    funds_amount = 1000
    print(f"💰  Adding some funds to the client balance: {funds_amount} uNIL")
    await client.add_funds(funds_amount)

    # Store the program
    print("Storing program...")
    program = open(program_mir_path, "rb").read()
    program_id = await client.store_program(CONFIG_PROGRAM_NAME, program).invoke()

    print(
        f"\n🎉1️⃣ Party {CONFIG_PARTY_1['party_name']} stored program using id {program_id}"
    )
    print("\n📋⬇️ Copy and run the following command to store N other party secrets")
    print(
        f"\npython3 02_store_secret_party_n.py --user_id_1 {user_id} --program_id {program_id}"
    )
    return [user_id, program_id]


if __name__ == "__main__":
    asyncio.run(main())


@pytest.mark.asyncio
async def test_main():
    pass
