name = "quickstart-example-programs"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/addition_simple.py"
prime_size = 128

[[programs]]
path = "src/addition_simple_multi_party.py"
prime_size = 128

[[programs]]
path = "src/circuit_simple_2.py"
prime_size = 128

[[programs]]
path = "src/correlation_coefficient.py"
prime_size = 128

[[programs]]
path = "src/division_simple.py"
prime_size = 128

[[programs]]
path = "src/greater_or_equal_than.py"
prime_size = 128

[[programs]]
path = "src/greater_than.py"
prime_size = 128

[[programs]]
path = "src/less_than.py"
prime_size = 128

[[programs]]
path = "src/literals.py"
prime_size = 128

[[programs]]
path = "src/millionaires.py"
prime_size = 128

[[programs]]
path = "src/modulo_simple.py"
prime_size = 128

[[programs]]
path = "src/multiplication_simple.py"
prime_size = 128

[[programs]]
path = "src/nada_fn_max.py"
prime_size = 128

[[programs]]
path = "src/public_variables.py"
prime_size = 128

[[programs]]
path = "src/reuse.py"
prime_size = 128

[[programs]]
path = "src/reuse_simple_sub_multi_party.py"
prime_size = 128

[[programs]]
path = "src/simple_sub.py"
prime_size = 128

[[programs]]
path = "src/single_addition_multi_party.py"
prime_size = 128

[[programs]]
path = "src/subtraction_simple.py"
prime_size = 128

[[programs]]
path = "src/subtraction_simple_neg.py"
prime_size = 128

[[programs]]
path = "src/voting_dishonest_abort_5.py"
prime_size = 128

[[programs]]
path = "src/voting_dishonest_robust_6.py"
prime_size = 128

[[programs]]
path = "src/voting_honest_1.py"
prime_size = 128

[[programs]]
path = "src/voting_honest_2.py"
prime_size = 128
